#注意：如果在记事本上编写，下面的缩进不要使用Tab来缩进，不然报错
spring:
  profiles:
    active: dev # 激活开发环境配置
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis配置文件所在路径
  type-aliases-package: com.liufan.springcloud.entity   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
spring:
  profiles: dev # 开发环境
  application:
    name: microservice-product-config    #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db01?serverTimezone=GMT%2B8
    username: root
    password: 123123123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}    # 指定实例ID,就不会显示主 机名了
    preferIpAddress: true #访问路径可以显示IP地址
---
server:
  port: 8001
mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml   # mybatis配置文件所在路径
  type-aliases-package: com.liufan.springcloud.entity   # 所有Entity别名类所在包
  mapper-locations: classpath:mybatis/mapper/**/*.xml     # mapper映射文件
spring:
  profiles: prod # 生产环境
  application:
    name: microservice-product-config    #这个很重要，这在以后的服务与服务之间相互调用一般都是根据这个
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springcloud_db02?serverTimezone=GMT%2B8
    username: root
    password: 123123123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 150

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka6001.com:6001/eureka/
  instance:
    instanceId: ${spring.application.name}:${server.port}    # 指定实例ID,就不会显示主 机名了
    preferIpAddress: true #访问路径可以显示IP地址
#保存时注意，选择 UTF-8 保存
